/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.customerRole;

import Business.Enterprise.Enterprise;
import Business.EcoSystem;
import Business.Organization.CustomerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.trashCollectWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumitjanawlekar
 */
public class customerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form customerWorkArea
     */
    private JPanel userProcessContainer;
    private CustomerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    public customerWorkArea(JPanel userProcessContainer, UserAccount account, CustomerOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.business =business;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }
    
     public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            
            Object[] row = new Object[4];
            row[0] = ((trashCollectWorkRequest)request).getTrashType();
            row[2] = ((trashCollectWorkRequest)request).getPickedUp();
            row[1] = request.getStatus();
            String result = ((trashCollectWorkRequest) request).getQuantityFinalized();
            row[3] = result == null ? "Not Finalized" : result;
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTrashBtn = new javax.swing.JButton();
        refreshTestBtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Trash Type", "Order Status", "PickedUp?", "Quantity Finalized"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 73, 743, 97));

        requestTrashBtn.setBackground(new java.awt.Color(255, 153, 0));
        requestTrashBtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        requestTrashBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestTrashBtn.setText("Request Trash");
        requestTrashBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTrashBtnActionPerformed(evt);
            }
        });
        add(requestTrashBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 215, 143, -1));

        refreshTestBtn.setBackground(new java.awt.Color(255, 153, 0));
        refreshTestBtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        refreshTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshTestBtn.setText("Refresh");
        refreshTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestBtnActionPerformed(evt);
            }
        });
        add(refreshTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 28, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        enterpriseLabel.setText("Customer Work Area:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 25, -1, 30));

        valueLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 157, 26));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 215, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestBtnActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_refreshTestBtnActionPerformed

    private void requestTrashBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTrashBtnActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("requestTrashCollect", new requestTrashCollect(userProcessContainer, userAccount, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTrashBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestBtn;
    private javax.swing.JButton requestTrashBtn;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
