/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.customerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CustomerOrganization;
import Business.Organization.OrderManagementOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.trashCollectWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sumitjanawlekar
 */
public class CustomerDashboardArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerDashboardArea
     */
    private JPanel userProcessContainer;
    private CustomerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    public CustomerDashboardArea(JPanel userProcessContainer, UserAccount account, CustomerOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.business =business;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
      populateData();
    }

    public void populateData(){
        int totalCreati = 0;
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            totalCreati += ((trashCollectWorkRequest)request).getRewards();
        }
     
        labelName.setText(userAccount.getEmployee().getName());
        labelUsername.setText(userAccount.getUsername());
        labelTotalCredits.setText(Integer.toString(totalCreati));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelTotalCredits = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  Dashboard");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 42, 711, 62));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 138, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Username :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 191, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Total Credits :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 253, -1, -1));

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelName.setText("<value>");
        add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 138, 130, -1));

        labelUsername.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelUsername.setText("<value>");
        add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 191, 130, -1));

        labelTotalCredits.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTotalCredits.setText("<value>");
        add(labelTotalCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 253, 130, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 458, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelTotalCredits;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
