/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.customerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CustomerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sumitjanawlekar
 */
public class ManageCustomerRole extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerRole
     */
    
    private JPanel userProcessContainer;
    private CustomerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    public ManageCustomerRole(JPanel userProcessContainer, UserAccount account, CustomerOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.business =business;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCustomerRequest = new javax.swing.JButton();
        btnManageManufacturerRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageCustomerRequest.setBackground(new java.awt.Color(255, 153, 0));
        btnManageCustomerRequest.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnManageCustomerRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCustomerRequest.setText("Manage My Request");
        btnManageCustomerRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerRequestActionPerformed(evt);
            }
        });
        add(btnManageCustomerRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 119, 193, -1));

        btnManageManufacturerRequest.setBackground(new java.awt.Color(255, 153, 0));
        btnManageManufacturerRequest.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnManageManufacturerRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnManageManufacturerRequest.setText("Manage My Dashboard");
        btnManageManufacturerRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageManufacturerRequestActionPerformed(evt);
            }
        });
        add(btnManageManufacturerRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 200, 193, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Customer Role");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 755, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCustomerRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerRequestActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("requestTrashCollect", new customerWorkArea(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCustomerRequestActionPerformed

    private void btnManageManufacturerRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageManufacturerRequestActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("requestTrashCollect", new CustomerDashboardArea(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageManufacturerRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCustomerRequest;
    private javax.swing.JButton btnManageManufacturerRequest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
