/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.customerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.WarehouseEnterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.OrderManagementOrganization;
import Business.Organization.Organization;
import Business.Role.OrderManagerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.trashCollectWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sumitjanawlekar
 */
public class requestTrashCollect extends javax.swing.JPanel {

    /** Creates new form requestTrashCollect */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    
    public requestTrashCollect(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(255, 153, 0));
        requestTestJButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setText("Request Trash");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 239, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Trash Type:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 143, -1, -1));

        backJButton.setBackground(new java.awt.Color(255, 153, 0));
        backJButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 239, -1, -1));

        valueLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 53, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        enterpriseLabel.setText("Customer Work Area:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 52, 233, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plastic", "Paper", "Metal" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 146, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String trashType = jComboBox1.getSelectedItem().toString();

        trashCollectWorkRequest request = new trashCollectWorkRequest();
        request.setTrashType(trashType);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setPickedUp("Not Picketup");
        request.setQuantityFinalized("Not Finalized");
        
        Organization or = null;
        for(Network network : business.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization org :  enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(org instanceof OrderManagementOrganization){
                        or = org;
                        break;
                    }
                }
            }
        }
        if(or != null){
            or.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(null, "Successfull");
        
        
//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if (organization instanceof CustomerOrganization){
//                org = organization;
//                break;
//            }
//        }
//        if (org!=null){
//            org.getWorkQueue().getWorkRequestList().add(request);
//            userAccount.getWorkQueue().getWorkRequestList().add(request);
//        }

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        customerWorkArea dwjp = (customerWorkArea) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
