/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManufacturerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CustomerOrganization;
import Business.Organization.ManufacturerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TrashOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.trashCollectWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumitjanawlekar
 */
public class ManufacturerWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ManufacturerWorkRequest
     */
    private JPanel userProcessContainer;
    private ManufacturerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    public ManufacturerWorkRequest(JPanel userProcessContainer, UserAccount account, ManufacturerOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.business =business;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }
    
         public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            
            Object[] row = new Object[4];
            row[0] = ((TrashOrderWorkRequest)request).getTrashType();
            row[2] = ((TrashOrderWorkRequest)request).getQuantity();
            row[1] = request.getStatus();
            
            String result = Integer.toString(((TrashOrderWorkRequest)request).getPrice()) ;
            row[3] = result == null ? "Not Finalized" : result;
            
            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestBtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTrashBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshTestBtn.setBackground(new java.awt.Color(255, 153, 0));
        refreshTestBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        refreshTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshTestBtn.setText("Refresh");
        refreshTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestBtnActionPerformed(evt);
            }
        });
        add(refreshTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 27, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        enterpriseLabel.setText("Work Area :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 28, 127, 30));

        valueLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 27, 158, 26));

        workRequestJTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trash Type", "Order Status", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 76, 721, 97));

        requestTrashBtn.setBackground(new java.awt.Color(255, 153, 0));
        requestTrashBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        requestTrashBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestTrashBtn.setText("Request Trash");
        requestTrashBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTrashBtnActionPerformed(evt);
            }
        });
        add(requestTrashBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 218, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestBtnActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_refreshTestBtnActionPerformed

    private void requestTrashBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTrashBtnActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("requestTrashCollect", new OrderTrash(userProcessContainer, userAccount, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTrashBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestBtn;
    private javax.swing.JButton requestTrashBtn;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
