/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LogisticsRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Organization.QualityCheckOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TrashOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.trashCollectWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumitjanawlekar
 */
public class LogisticsWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsWorkRequest
     */
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private LogisticsOrganization logisticsOrganization;
    private Enterprise enterprise;
    
    public LogisticsWorkRequest(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        this.logisticsOrganization = (LogisticsOrganization)organization;
        
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : logisticsOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof trashCollectWorkRequest){
            Object[] row = new Object[4];
            row[0] = ((trashCollectWorkRequest)request);
            row[1] = request.getSender().getEmployee().getName();
            row[2] = ((trashCollectWorkRequest)request).getDeliveryBoyName() == null ? null : ((trashCollectWorkRequest)request).getDeliveryBoyName();
            row[3] = ((trashCollectWorkRequest)request).getPickedUp();
            
            model.addRow(row);
            }
            
            if(request instanceof TrashOrderWorkRequest){
            Object[] row = new Object[4];
            row[0] = ((TrashOrderWorkRequest)request);
            row[1] = request.getSender().getEmployee().getName();
            row[2] = ((TrashOrderWorkRequest)request).getDeliveryBoyName() == null ? null : ((TrashOrderWorkRequest)request).getDeliveryBoyName();
            row[3] = ((TrashOrderWorkRequest)request).getPickedUp();
            
            model.addRow(row);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton2 = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Trash Type", "Sender", "Delivery Boy Assigned", "Delivery Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 784, 96));

        assignJButton2.setBackground(new java.awt.Color(255, 153, 0));
        assignJButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assignJButton2.setForeground(new java.awt.Color(255, 255, 255));
        assignJButton2.setText("Assign to me");
        assignJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButton2ActionPerformed(evt);
            }
        });
        add(assignJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 319, -1, -1));

        processJButton.setBackground(new java.awt.Color(255, 153, 0));
        processJButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        processJButton.setForeground(new java.awt.Color(255, 255, 255));
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, -1, -1));

        refreshJButton.setBackground(new java.awt.Color(255, 153, 0));
        refreshJButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 153, 0));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Logistics Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButton2ActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        

        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        if(request instanceof trashCollectWorkRequest){
            request.setDeliveryBoyName(userAccount);
        }
        else{
            request.setDeliveryBoyName(userAccount);
        }
       
        if(request.getPickedUp().equalsIgnoreCase("Pickedup")){
            JOptionPane.showMessageDialog(null, "Cannot pick up this item");
        }
        else if(request.getPickedUp().equalsIgnoreCase("Delivered"))
        {
            JOptionPane.showMessageDialog(null, "Item already delivered,Please select another item");
        }
        else{
            if(request instanceof trashCollectWorkRequest){
                request.setPickedUp("Pickedup");
            }
            else{
                request.setPickedUp("Pickedup");
            }
        }
      
        populateTable();
        
    }//GEN-LAST:event_assignJButton2ActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        
        if(request instanceof trashCollectWorkRequest){
          
        }
        
        else{
            
        }
        if(request.getPickedUp().equalsIgnoreCase("Pickedup")){
            
        request.setPickedUp("Delivered");
        }
        else if(request.getPickedUp().equalsIgnoreCase("Delivered"))
        {
            JOptionPane.showMessageDialog(null, "Item already delivered,Please select another item");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please assign to yourself first");
        }
         populateTable();
        
        
//        ProcessLogisticsWorkRequestJPanel processLogisticsRequestJPanel = new ProcessLogisticsWorkRequestJPanel(userProcessContainer,request,userAccount,logisticsOrganization, enterprise, business);
//        userProcessContainer.add("processLogisticsRequestJPanels", processLogisticsRequestJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton2;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
